import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";
import { AppProviders } from "@/components/AppProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          <div className="min-h-dvh flex bg-zinc-50">
            <aside className="w-20 shrink-0 bg-slate-900 text-white flex flex-col items-center py-4 gap-4">
              <div className="h-10 w-10 rounded bg-white/10 grid place-items-center font-bold">S</div>
              <NavItem href="/" label="ホーム" icon="🏠" />
              <NavItem href="/data" label="納品データ" icon="📄" />
              <NavItem href="/upload" label="アップロード" icon="⬆️" />
              <NavItem href="/suppliers" label="仕入先" icon="👥" />
              <NavItem href="/analysis" label="分析" icon="📊" />
              <NavItem href="/drive-imports" label="Drive保留" icon="📁" />
              <div className="mt-auto" />
            </aside>
            <main className="flex-1 min-w-0">
              <header className="h-14 bg-white border-b flex items-center justify-between px-4">
                <input placeholder="検索" className="w-[320px] h-9 rounded border px-3 text-sm" />
                <div className="flex items-center gap-3 text-sm text-slate-700">
                  <button aria-label="通知">🔔</button>
                  <span>ユーザー</span>
                </div>
              </header>
              <div className="p-6">{children}</div>
            </main>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}

function NavItem({ href, label, icon }: { href: string; label: string; icon: string }) {
  return (
    <Link href={href} className="w-12 h-12 rounded-md grid place-items-center hover:bg-white/10" title={label}>
      <span aria-hidden>{icon}</span>
    </Link>
  );
}
